---
meta:
  environment: apps.cityindex.logsearch.io

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

director_uuid: f38e81de-d07b-4b56-b691-4f005745575b

releases:
  - name: cf
    version: 169

networks:
  - name: z1_public
    type: manual
    subnets:
    - range: 10.13.0.0/21
      name: eu-west-1a/public
      reserved:
      - 10.13.0.0 - 10.13.0.9
      static:
      - 10.13.0.0 - 10.13.0.254  # How do we avoid conflicting with other deployments in this subnet?
      gateway: 10.13.0.0.1
    cloud_properties:
      subnet: "subnet-aaaaaa"
      security_groups:
      - "vpc-internal-all"
      - "trusted-web"
  - name: z1_private
    type: manual
    subnets:
    - range: 10.13.8.0/21
      name: eu-west-1a/public
      reserved:
      - 10.13.8.2 - 10.13.8.9
      static:
      - 10.13.8.10 - 10.13.8.254
      gateway: 10.13.8.1
    cloud_properties:
      subnet: "subnet-bbbbbb"
      security_groups:
      - "vpc-internal-all"
  - name: z2_public
    type: manual
    subnets:
    - range: 10.13.16.0.0/21
      name: eu-west-1b/public
      reserved:
      - 10.13.16.2 - 10.13.16.9
      static:
      - 10.13.16.10 - 10.13.16.254
      gateway: 10.13.16.1
      cloud_properties:
        subnet: "subnet-ccccccc"
        security_groups:
        - "vpc-internal-all"
        - "trusted-web"
  - name: z2_private
    type: manual
    subnets:
    - range: 10.13.24.0.0/21
      name: eu-west-1b/private
      reserved:
      - 10.13.24.2 - 10.13.24.9
      static:
      - 10.13.24.10 - 10.13.24.254
      gateway: 10.13.24.1
      cloud_properties:
        subnet: "subnet-dddddd"
        security_groups:
        - "vpc-internal-all"

# Switch jobs on and off here
jobs:
  - name: postgres_z1 #NB - these appear to be SPOFs
    instances: 1
  - name: ha_proxy_z1 #SPOF?
    instances: 1

  - name: nats_z1
    instances: 1
  - name: nats_z2
    instances: 1

  - name: api_z1
    instances: 1
  - name: api_z2
    instances: 0

  - name: api_worker_z1
    instances: 0
  - name: api_worker_z2
    instances: 0

  - name: clock_global
    instances: 0

  - name: etcd_leader_z1
    instances: 1
  - name: etcd_z1
    instances: 0
  - name: etcd_z2
    instances: 0

  - name: router_z1
    instances: 1
  - name: router_z2
    instances: 0

  - name: runner_z1
    instances: 1
  - name: runner_z2
    instances: 0

  - name: uaa_z1
    instances: 1
  - name: uaa_z2
    instances: 0

  - name: hm9000_z1
    instances: 1
  - name: hm9000_z2
    instances: 0

  - name: loggregator_trafficcontroller_z1
    instances: 1
  - name: loggregator_trafficcontroller_z2
    instances: 0

  - name: loggregator_z1
    instances: 1
  - name: loggregator_z2
    instances: 0

#NOT USED
  - name: login_z1  
    instances: 0

  - name: stats_z1
    instances: 0
  - name: stats_z2
    instances: 0    

  - name: logs_z1
    instances: 0
  - name: logs_z1
    instances: 0   

properties:
  domain: apps.cityindex.logsearch.io

  cc:
    srv_api_uri: (( "http://api." domain ))

  dea_next:
    memory_mb: 81960
    disk_mb: 100000

  template_only:
    aws:
      availability_zone: eu-west-1a
      availability_zone2: eu-west-1b
      subnet_ids:
        cf1: subnet-dfd021ba
        cf2: subnet-27c9d453

  login:
    protocol: http

  uaa:
    no_ssl: true
