---
meta:
  environment: apps.cityindex.logsearch.io

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest

director_uuid: f38e81de-d07b-4b56-b691-4f005745575b

releases:
  - name: cf
    version: 169

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: cf1
    type: manual
    subnets:
    - range: 10.13.1.16/28
      name: main/eu-west-1a/public/apps.cityindex.logsearch.io
      static:
      - 10.13.1.17 - 10.13.1.23  # dynamic: 10.13.1.24 - 10.13.1.31
    cloud_properties:
      subnet: "subnet-dfd021ba"
      security_groups:
      - "cradle-cityindex-logsearch-io-VPC-QN3W2O3CCFTS-SecuritygroupInternalAll-6GY3CNMM6S73" # internal-all
      - "cradle-cityindex-logsearch-io-SecurityGroups-1BICD6I7VV7VO-TrustedWeb-46RU0YIUT1YD" # trusted-web
  - name: cf2
    type: manual
    subnets:
    - range: 10.13.17.16/28
      name: main/eu-west-1b/public/apps.cityindex.logsearch.io
      static:
      - 10.13.17.17 - 10.13.17.23  # dynamic: 10.13.17.24 - 10.13.17.31
      cloud_properties:
        subnet: "subnet-27c9d453"
        security_groups:
        - "cradle-cityindex-logsearch-io-VPC-QN3W2O3CCFTS-SecuritygroupInternalAll-6GY3CNMM6S73" # internal-all
        - "cradle-cityindex-logsearch-io-SecurityGroups-1BICD6I7VV7VO-TrustedWeb-46RU0YIUT1YD" # trusted-web

# Switch jobs on and off here
jobs:
  - name: postgres_z1 #NB - these appear to be SPOFs
    instances: 1
  - name: ha_proxy_z1 #SPOF?
    instances: 1
    networks:
      - name: floating
        static_ips: 54.72.132.94

  - name: nats_z1
    instances: 1
  - name: nats_z2
    instances: 1

  - name: api_z1
    instances: 1
  - name: api_z2
    instances: 0

  - name: api_worker_z1
    instances: 0
  - name: api_worker_z2
    instances: 0

  - name: clock_global
    instances: 0

  - name: etcd_leader_z1
    instances: 1
  - name: etcd_z1
    instances: 0
  - name: etcd_z2
    instances: 0

  - name: router_z1
    instances: 1
  - name: router_z2
    instances: 0

  - name: runner_z1
    instances: 1
  - name: runner_z2
    instances: 0

  - name: uaa_z1
    instances: 1
  - name: uaa_z2
    instances: 0

  - name: hm9000_z1
    instances: 1
  - name: hm9000_z2
    instances: 0

  - name: loggregator_trafficcontroller_z1
    instances: 1
  - name: loggregator_trafficcontroller_z2
    instances: 0

  - name: loggregator_z1
    instances: 1
  - name: loggregator_z2
    instances: 0

#NOT USED
  - name: login_z1  
    instances: 0

  - name: stats_z1
    instances: 0
  - name: stats_z2
    instances: 0    

  - name: logs_z1
    instances: 0
  - name: logs_z1
    instances: 0   

properties:
  domain: apps.cityindex.logsearch.io

  cc:
    srv_api_uri: (( "http://api." domain ))

  dea_next:
    memory_mb: 8196
    disk_mb: 10000

  template_only:
    aws:
      availability_zone: eu-west-1a
      availability_zone2: eu-west-1b
      subnet_ids:
        cf1: subnet-dfd021ba
        cf2: subnet-27c9d453

  login:
    protocol: http

  uaa:
    no_ssl: true
