---
director_uuid: f0588560-08a8-4ae2-914a-b9e8b12d9303

releases:
  - name: cf
    version: 169

# Switch jobs on and off here
jobs:
  - name: postgres_z1  #NB - these appear to be SPOFs
    instances: 1

  - name: ha_proxy_z1 #SPOF?
    instances: 1

  - name: login_z1  #SPOF?
    instances: 1

  - name: nats_z1
    instances: 1
  - name: nats_z2
    instances: 0

  - name: api_z1
    instances: 1
  - name: api_z2
    instances: 0

  - name: api_worker_z1
    instances: 0
  - name: api_worker_z2
    instances: 0

  - name: clock_global
    instances: 0
  - name: etcd_leader_z1
    instances: 1

  - name: etcd_z1
    instances: 0
  - name: etcd_z2
    instances: 0

  - name: router_z1
    instances: 1
  - name: router_z2
    instances: 1

  - name: runner_z1
    instances: 1
  - name: runner_z2
    instances: 0

  - name: uaa_z1
    instances: 1
  - name: uaa_z2
    instances: 0

  - name: hm9000_z1
    instances: 1
  - name: hm9000_z2
    instances: 0

  - name: loggregator_trafficcontroller_z1
    instances: 1
  - name: loggregator_trafficcontroller_z2
    instances: 0

  - name: loggregator_z1
    instances: 1
  - name: loggregator_z2
    instances: 0

#NOT USED
  - name: stats_z1
    instances: 0
  - name: stats_z2
    instances: 0    

  - name: logs_z1
    instances: 0
  - name: logs_z1
    instances: 0    
