meta:
  zones:
    z1: (( properties.template_only.aws.availability_zone ))
    z2: (( properties.template_only.aws.availability_zone2 ))
    z3: (( properties.template_only.aws.availability_zone3 ))

  fog_config:
    provider: AWS
    path_style: true # allow . in the S3 bucket names
    aws_access_key_id: (( properties.template_only_aws_credentials.access_key_id ))
    aws_secret_access_key: (( properties.template_only_aws_credentials.secret_access_key ))
    region: (( properties.template_only.aws.region ))

  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest


properties:
  template_only: (( merge ))
  template_only_aws_credentials: (( merge ))

  logger_endpoint:
    port: 4443

  loggregator:
    blacklisted_syslog_ranges:
    - start: 10.13.16.0
      end: 10.13.31.255
    - start: 10.13.80.0
      end: 10.13.95.255

  cc:
    resource_pool:
      fog_connection: (( meta.fog_config ))
    packages:
      fog_connection: (( meta.fog_config ))
    droplets:
      fog_connection: (( meta.fog_config ))
    buildpacks:
      fog_connection: (( meta.fog_config ))

  uaa:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m

  login:
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m

  dea_next:
    memory_mb: 17408 # For 17GB m2.xlarge
    disk_mb: 320000 # 320GB
    deny_networks:
      - 169.254.0.0/16 # AWS Status
      - 10.13.0.0/24 # BOSH network & other core services (eg, NAT instance)
      - (( networks.cf1_public.subnets.[0].range ))
      - (( networks.cf1.subnets.[0].range ))
      - (( networks.cf2_public.subnets.[0].range ))
      - (( networks.cf2.subnets.[0].range ))

    allow_networks:
      - 10.13.0.2/32 # Amazon DNS

  ccdb:
    db_scheme: postgres
    address: (( properties.databases.address ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true

  uaadb:
    db_scheme: postgresql
    address: (( properties.databases.address ))
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  databases:
    db_scheme: postgres
    address: (( jobs.postgres_z1.networks.cf1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

compilation:
  cloud_properties:
    instance_type: c1.medium
    availability_zone: (( meta.zones.z1 ))

networks: (( merge ))

resource_pools:
  - name: small_ondemand_z1
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( meta.zones.z1 ))

  - name: small_z1
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( meta.zones.z1 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m1_small ))

  - name: small_z2
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( meta.zones.z2 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m1_small ))

  - name: small_z3
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( meta.zones.z3 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m1_small ))

  - name: medium_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( meta.zones.z1 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_medium ))

  - name: medium_z2
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( meta.zones.z2 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_medium ))

  - name: medium_z3
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( meta.zones.z3 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_medium ))

  - name: large_z1
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( meta.zones.z1 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_large ))

  - name: large_z2
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( meta.zones.z2 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_large ))

  - name: large_z3
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( meta.zones.z3 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_large ))

  - name: runner_z1
    cloud_properties:
      instance_type: m2.xlarge
      availability_zone: (( meta.zones.z1 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m2_xlarge ))

  - name: runner_z2
    cloud_properties:
      instance_type: m2.xlarge
      availability_zone: (( meta.zones.z2 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m2_xlarge ))

  - name: runner_z3
    cloud_properties:
      instance_type: m2.xlarge
      availability_zone: (( meta.zones.z3 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m2_xlarge ))

  - name: router_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( meta.zones.z1 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_medium ))

  - name: router_z2
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( meta.zones.z2 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_medium ))

  - name: router_z3
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( meta.zones.z3 ))
      spot_bid_price: (( properties.template_only.aws.spot_bid_prices.m3_medium ))

  - name: small_errand
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( meta.zones.z1 ))


# set up static IPs
jobs:

  - name: ha_proxy_z1
    instances: 1
    networks:
      - name: cf1_public
        static_ips: (( static_ips(1) ))
        default: 
        - dns
        - gateway
      - name: floating
        static_ips: ~

  - name: ha_proxy_z2
    instances: 0
    networks:
      - name: cf2_public
        static_ips: (( static_ips(1) ))
        default: 
        - dns
        - gateway
      - name: floating
        static_ips: ~

  - name: ha_proxy_z3
    instances: 0
    networks:
      - name: cf3_public
        static_ips: (( static_ips(1) ))
        default: 
        - dns
        - gateway
      - name: floating
        static_ips: ~

  - name: logs_z1
    instances: 0
    networks:
      - name: cf1
        static_ips: (( static_ips(0) ))

  - name: logs_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: (( static_ips(0) ))

  - name: logs_z3
    instances: 0
    networks:
      - name: cf3
        static_ips: (( static_ips(0) ))

  - name: nats_z1
    instances: 0
    networks:
      - name: cf1
        static_ips: (( static_ips(1) ))

  - name: nats_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: (( static_ips(1) ))

  - name: nats_z3
    instances: 0
    networks:
      - name: cf3
        static_ips: (( static_ips(1) ))

  - name: router_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(5, 6, 15, 16, 17, 18, 19, 20) ))

  - name: router_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: (( static_ips(5, 6, 15, 16, 17, 18, 19, 20) ))

  - name: router_z3
    instances: 0
    networks:
      - name: cf3
        static_ips: (( static_ips(5, 6, 15, 16, 17, 18, 19, 20) ))

  - name: loggregator_z1
    instances: 2
    networks:
      - name: cf1
        static_ips: (( static_ips(21, 22) ))

  - name: loggregator_z2
    instances: 0
    networks:
      - name: cf2
        static_ips: (( static_ips(21, 22) ))

  - name: loggregator_z3
    instances: 0
    networks:
      - name: cf3
        static_ips: (( static_ips(21, 22) ))

  - name: loggregator_trafficcontroller_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(24) ))

  - name: loggregator_trafficcontroller_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: (( static_ips(24) ))

  - name: loggregator_trafficcontroller_z3
    instances: 0
    networks:
      - name: cf3
        static_ips: (( static_ips(24) ))

  - name: etcd_z1
    instances: 2
    networks:
      - name: cf1
        static_ips: (( static_ips(10, 25) ))

  - name: etcd_z2
    instances: 1
    networks:
      - name: cf2
        static_ips: (( static_ips(9) ))

  - name: etcd_z3
    instances: 0
    networks:
      - name: cf3
        static_ips: (( static_ips(9) ))

 # SPOFs
  - name: postgres_z1
    instances: 1
    networks:
    - name: cf1
      static_ips: (( static_ips(7) ))
